FROM apache/airflow:1.10.15-python3.7
ADD ./pyproject.toml ./pyproject.toml
ADD ./README.md ./README.md
ADD ./odd_airflow ./odd_airflow
RUN pip install . --extra-index-url https://test.pypi.org/simple/
